# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

before_script:
  - unset http_proxy
  - unset https_proxy
  - env
  - npm ci
pages:
  tags:
    - docker
    - linux
  cache:
    paths:
      - node_modules/
  script:
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
